# Generated by Django 3.2.25 on 2024-10-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('cover', models.ImageField(upload_to='cover')),
                ('pdf', models.FileField(upload_to='pdf')),
            ],
        ),
    ]
